version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    registries: "*"
    groups:
      all:
        patterns:
          - "*"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/"
    registries: "*"
    groups:
      all:
        patterns:
          - "*"
    schedule:
      interval: "daily"

