[tools]
"cargo:wasm-pack" = "latest"
gitleaks = "latest"
lefthook = "latest"
node = "26"
"npm:@commitlint/cli" = "latest"
"npm:@commitlint/config-conventional" = "latest"
"npm:npm-check-updates" = "latest"
pnpm = "latest"
rust = "latest"

[tasks.ncu]
run = "npm-check-updates -u"
