name: Build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - name: Restore cache pnpm-store
      id: node_modules_cache
      uses: actions/cache@v4
      with:
        save-always: true
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-${{ matrix.node-version }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node-version }}-pnpm-store-
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
    - name: Cargo install
      run: |
        cargo install wasm-pack -f
    - name: Run biome migrate
      run: pnpm biome migrate --write
    - name: Run Linter/Formatter
      if: ${{ github.event_name == 'pull_request' }}
      run: pnpm run lint
    - name: Run Typescript check
      if: ${{ github.event_name == 'pull_request' }}
      run: pnpm run check
    - name: Run Tests
      run: pnpm run test
    - name: Run build
      run: pnpm run build
